name: Static analysis

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - '**.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.base.sha }}
    - uses: actions/checkout@v4
    - name: Enable Problem Matchers
      run: echo "::add-matcher::.github/shellcheck-matcher.json"
    - name: Check scripts with shellcheck
      run: |
        git diff ${{ github.event.pull_request.base.sha }}.. \
          --diff-filter=AM --name-only -- '*.sh' | while read script ; do \
            shellcheck ${EXCLUDE_OPTS:+-e ${EXCLUDE_OPTS}} $script || touch error ; \
        done
        echo "::remove-matcher owner=shellcheck-matcher::"
        test ! -e error
